name: Upload to fwfy.club
on:
  push:
    branches:
      - "dev"
jobs:
  build:
    name: Publish to site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy files over SCP to web host.
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        source: "index.html,dust.js"
        target: /var/www/fwfy.club/dust/dev
        key: ${{ secrets.KEY }}
        rm: false
